language: java
sudo: required

env:
  - USE_LOCAL_DRIVER=true
  - USE_REMOTE_DRIVER=true REMOTE_DRIVER_USERNAME=$SAUCELABS_USERNAME REMOTE_DRIVER_USERNAME=$SAUCELABS_PASSWORD REMOTE_DRIVER_URL=ondemand.saucelabs.com:443/wd/hub
  - USE_REMOTE_DRIVER=true USE_CBT=true REMOTE_DRIVER_USERNAME=$CBT_USERNAME REMOTE_DRIVER_USERNAME=$CBT_PASSWORD REMOTE_DRIVER_URL=hub.crossbrowsertesting.com:80/wd/hub


addons:
  chrome: stable

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - hiptest-publisher -c junit-selenium.conf --token=$SECRET_TOKEN --only=tests --test-run-id=101683

install:
  - wget -N https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

script:
  - whereis google-chrome-stable
  - mvn package

after_script:
  - hiptest-publisher -c junit-selenium.conf --token=$SECRET_TOKEN -p "target/surefire-reports/TEST-com.coffeemachine.*.xml" --test-run-id=101683
